In [1]:
import outp_parser
import json

### Tally Parsing and Saving Example

In [5]:
# Find file.
outp_path = "c100w_plateflux_production_09052025.outp"
# Make a tallies dictionary from output.
tally_dict = outp_parser.get_tallies(outp_path)
# Check to make sure the first key can be accessed.
tally_dict['Assembly MTR-F-001, Element #1']

[[20.0,
  6.434,
  4.304,
  3.0,
  1.85,
  1.5,
  1.2,
  0.8611,
  0.75,
  0.6,
  0.47,
  0.33,
  0.27,
  0.2,
  0.05,
  0.02,
  0.017,
  0.00374,
  0.00225,
  0.0001915,
  0.0001877,
  0.0001175,
  0.000116,
  0.000105,
  0.0001012,
  6.75e-05,
  6.5e-05,
  3.713e-05,
  3.6e-05,
  2.175e-05,
  2.12e-05,
  2.05e-05,
  7e-06,
  6.875e-06,
  6.5e-06,
  6.25e-06,
  5e-06,
  1.13e-06,
  1.08e-06,
  1.01e-06,
  6.25e-07,
  4.5e-07,
  3.75e-07,
  3.5e-07,
  3.25e-07,
  2.5e-07,
  2e-07,
  1.5e-07,
  1e-07,
  8e-08,
  6e-08,
  5e-08,
  4e-08,
  2.53e-08,
  1e-08,
  4e-09,
  1e-11],
 [6.20595e-05,
  0.000221995,
  0.000403066,
  0.000781542,
  0.0003465,
  0.000358204,
  0.000457929,
  0.00020404,
  0.000291654,
  0.000262472,
  0.000303122,
  0.000161084,
  0.000204052,
  0.000661394,
  0.000307537,
  5.02355e-05,
  0.000430194,
  0.000137404,
  0.000638476,
  4.3492e-06,
  0.000117143,
  2.56036e-06,
  2.5074e-05,
  8.17041e-06,
  9.90313e-05,
  8.40235e-06,
  0.00013472,
  5.38126e-06,
  0.

In [7]:
# Produce desired filepath to JSON file.
json_path = "c100w_plateflux_production_09052025.outp"
# Dump the dictionary to the JSON file.
with open(json_path, 'w') as f:
    json.dump(tally_dict, f)

### Tally Loading

In [8]:
# Load the JSON file.
with open(json_path, 'r') as jsonfile:
    loaded_tallies = json.load(jsonfile)
# Check to see if the first key is present.
loaded_tallies['Assembly MTR-F-001, Element #1']

[[20.0,
  6.434,
  4.304,
  3.0,
  1.85,
  1.5,
  1.2,
  0.8611,
  0.75,
  0.6,
  0.47,
  0.33,
  0.27,
  0.2,
  0.05,
  0.02,
  0.017,
  0.00374,
  0.00225,
  0.0001915,
  0.0001877,
  0.0001175,
  0.000116,
  0.000105,
  0.0001012,
  6.75e-05,
  6.5e-05,
  3.713e-05,
  3.6e-05,
  2.175e-05,
  2.12e-05,
  2.05e-05,
  7e-06,
  6.875e-06,
  6.5e-06,
  6.25e-06,
  5e-06,
  1.13e-06,
  1.08e-06,
  1.01e-06,
  6.25e-07,
  4.5e-07,
  3.75e-07,
  3.5e-07,
  3.25e-07,
  2.5e-07,
  2e-07,
  1.5e-07,
  1e-07,
  8e-08,
  6e-08,
  5e-08,
  4e-08,
  2.53e-08,
  1e-08,
  4e-09,
  1e-11],
 [6.20595e-05,
  0.000221995,
  0.000403066,
  0.000781542,
  0.0003465,
  0.000358204,
  0.000457929,
  0.00020404,
  0.000291654,
  0.000262472,
  0.000303122,
  0.000161084,
  0.000204052,
  0.000661394,
  0.000307537,
  5.02355e-05,
  0.000430194,
  0.000137404,
  0.000638476,
  4.3492e-06,
  0.000117143,
  2.56036e-06,
  2.5074e-05,
  8.17041e-06,
  9.90313e-05,
  8.40235e-06,
  0.00013472,
  5.38126e-06,
  0.

In [9]:
# Load the tallies dictionary as DataFrames.
tally_dfs = outp_parser.conv_tallies(loaded_tallies)
# Check if the first key is a DataFrame now.
tally_dfs['Assembly MTR-F-001, Element #1']

energy      flux     std
0   2.000000e+01  0.000062  0.0077
1   6.434000e+00  0.000222  0.0039
2   4.304000e+00  0.000403  0.0030
3   3.000000e+00  0.000782  0.0021
4   1.850000e+00  0.000347  0.0032
5   1.500000e+00  0.000358  0.0031
6   1.200000e+00  0.000458  0.0028
7   8.611000e-01  0.000204  0.0038
8   7.500000e-01  0.000292  0.0033
9   6.000000e-01  0.000262  0.0035
10  4.700000e-01  0.000303  0.0032
11  3.300000e-01  0.000161  0.0042
12  2.700000e-01  0.000204  0.0037
13  2.000000e-01  0.000661  0.0021
14  5.000000e-02  0.000308  0.0030
15  2.000000e-02  0.000050  0.0076
16  1.700000e-02  0.000430  0.0025
17  3.740000e-03  0.000137  0.0043
18  2.250000e-03  0.000638  0.0021
19  1.915000e-04  0.000004  0.0247
20  1.877000e-04  0.000117  0.0047
21  1.175000e-04  0.000003  0.0265
22  1.160000e-04  0.000025  0.0096
23  1.050000e-04  0.000008  0.0163
24  1.012000e-04  0.000099  0.0050
25  6.750000e-05  0.000008  0.0155
26  6.500000e-05  0.000135  0.0044
27  3.713000e-05  0.000005  0.0172
28  3.600000e-05  0.000119  0.0048
29  2.175000e-05  0.000006  0.0175
30  2.120000e-05  0.000005  0.0163
31  2.050000e-05  0.000244  0.0032
32  7.000000e-06  0.000004  0.0224
33  6.875000e-06  0.000006  0.0145
34  6.500000e-06  0.000008  0.0148
35  6.250000e-06  0.000049  0.0068
36  5.000000e-06  0.000336  0.0028
37  1.130000e-06  0.000010  0.0139
38  1.080000e-06  0.000015  0.0117
39  1.010000e-06  0.000115  0.0047
40  6.250000e-07  0.000082  0.0054
41  4.500000e-07  0.000046  0.0068
42  3.750000e-07  0.000017  0.0113
43  3.500000e-07  0.000019  0.0107
44  3.250000e-07  0.000067  0.0054
45  2.500000e-07  0.000064  0.0057
46  2.000000e-07  0.000107  0.0044
47  1.500000e-07  0.000242  0.0029
48  1.000000e-07  0.000188  0.0031
49  8.000000e-08  0.000278  0.0025
50  6.000000e-08  0.000180  0.0030
51  5.000000e-08  0.000204  0.0028
52  4.000000e-08  0.000323  0.0023
53  2.530000e-08  0.000286  0.0025
54  1.000000e-08  0.000060  0.0047
55  4.000000e-09  0.000012  0.0092
56  1.000000e-11  0.000000  0.0000

### Handling

In [10]:
# Get the keys from a dictionary.
keys = tally_dfs.keys()
# Check the keys.
keys

dict_keys(['Assembly MTR-F-001, Element #1', 'Assembly MTR-F-001, Element #2', 'Assembly MTR-F-001, Element #3', 'Assembly MTR-F-001, Element #4', 'Assembly MTR-F-001, Element #5', 'Assembly MTR-F-001, Element #6', 'Assembly MTR-F-001, Element #7', 'Assembly MTR-F-001, Element #8', 'Assembly MTR-F-001, Element #9', 'Assembly MTR-F-001, Element #10', 'Assembly MTR-F-001, Element #11', 'Assembly MTR-F-001, Element #12', 'Assembly MTR-F-001, Element #13', 'Assembly MTR-F-001, Element #14', 'Assembly MTR-F-001, Element #15', 'Assembly MTR-F-001, Element #16', 'Assembly MTR-F-001, Element #17', 'Assembly MTR-F-001, Element #18', 'Assembly MTR-F-002, Element #1', 'Assembly MTR-F-002, Element #2', 'Assembly MTR-F-002, Element #3', 'Assembly MTR-F-002, Element #4', 'Assembly MTR-F-002, Element #5', 'Assembly MTR-F-002, Element #6', 'Assembly MTR-F-002, Element #7', 'Assembly MTR-F-002, Element #8', 'Assembly MTR-F-002, Element #9', 'Assembly MTR-F-002, Element #10', 'Assembly MTR-F-002, Elemen

In [17]:
# Cycle through all keys in a dictionary.
tallies_data = []
for key in keys:
    this_tally = tally_dfs[key]
    tallies_data.append(this_tally)
# Check to make sure all the tallies were pulled.
len(tallies_data)

252

In [12]:
# Convert a DataFrame to a numpy array.
tally_np = tally_dfs['Assembly MTR-F-001, Element #1'].to_numpy()
# Check it.
tally_np

array([[2.00000e+01, 6.20595e-05, 7.70000e-03],
       [6.43400e+00, 2.21995e-04, 3.90000e-03],
       [4.30400e+00, 4.03066e-04, 3.00000e-03],
       [3.00000e+00, 7.81542e-04, 2.10000e-03],
       [1.85000e+00, 3.46500e-04, 3.20000e-03],
       [1.50000e+00, 3.58204e-04, 3.10000e-03],
       [1.20000e+00, 4.57929e-04, 2.80000e-03],
       [8.61100e-01, 2.04040e-04, 3.80000e-03],
       [7.50000e-01, 2.91654e-04, 3.30000e-03],
       [6.00000e-01, 2.62472e-04, 3.50000e-03],
       [4.70000e-01, 3.03122e-04, 3.20000e-03],
       [3.30000e-01, 1.61084e-04, 4.20000e-03],
       [2.70000e-01, 2.04052e-04, 3.70000e-03],
       [2.00000e-01, 6.61394e-04, 2.10000e-03],
       [5.00000e-02, 3.07537e-04, 3.00000e-03],
       [2.00000e-02, 5.02355e-05, 7.60000e-03],
       [1.70000e-02, 4.30194e-04, 2.50000e-03],
       [3.74000e-03, 1.37404e-04, 4.30000e-03],
       [2.25000e-03, 6.38476e-04, 2.10000e-03],
       [1.91500e-04, 4.34920e-06, 2.47000e-02],
       [1.87700e-04, 1.17143e-04, 4.7000

In [13]:
# Pull the energy 'column' from numpy.
# Note that '.T' is a transpose operation.
energies = tally_np.T[0]

In [14]:
# Pull the energy 'column' from the DataFrame as a numpy array.
energies = tally_dfs['Assembly MTR-F-001, Element #1']['energy'].to_numpy()
# Check it.
energies

array([2.000e+01, 6.434e+00, 4.304e+00, 3.000e+00, 1.850e+00, 1.500e+00,
       1.200e+00, 8.611e-01, 7.500e-01, 6.000e-01, 4.700e-01, 3.300e-01,
       2.700e-01, 2.000e-01, 5.000e-02, 2.000e-02, 1.700e-02, 3.740e-03,
       2.250e-03, 1.915e-04, 1.877e-04, 1.175e-04, 1.160e-04, 1.050e-04,
       1.012e-04, 6.750e-05, 6.500e-05, 3.713e-05, 3.600e-05, 2.175e-05,
       2.120e-05, 2.050e-05, 7.000e-06, 6.875e-06, 6.500e-06, 6.250e-06,
       5.000e-06, 1.130e-06, 1.080e-06, 1.010e-06, 6.250e-07, 4.500e-07,
       3.750e-07, 3.500e-07, 3.250e-07, 2.500e-07, 2.000e-07, 1.500e-07,
       1.000e-07, 8.000e-08, 6.000e-08, 5.000e-08, 4.000e-08, 2.530e-08,
       1.000e-08, 4.000e-09, 1.000e-11])

In [ ]:
# Pull the energy, flux and standard deviations into a single tuple.
data = tuple(vals[:-1] for vals in tally_np.T) # Exclude the last column to create 56 group. 
# Check it.
data

(array([2.000e+01, 6.434e+00, 4.304e+00, 3.000e+00, 1.850e+00, 1.500e+00,
        1.200e+00, 8.611e-01, 7.500e-01, 6.000e-01, 4.700e-01, 3.300e-01,
        2.700e-01, 2.000e-01, 5.000e-02, 2.000e-02, 1.700e-02, 3.740e-03,
        2.250e-03, 1.915e-04, 1.877e-04, 1.175e-04, 1.160e-04, 1.050e-04,
        1.012e-04, 6.750e-05, 6.500e-05, 3.713e-05, 3.600e-05, 2.175e-05,
        2.120e-05, 2.050e-05, 7.000e-06, 6.875e-06, 6.500e-06, 6.250e-06,
        5.000e-06, 1.130e-06, 1.080e-06, 1.010e-06, 6.250e-07, 4.500e-07,
        3.750e-07, 3.500e-07, 3.250e-07, 2.500e-07, 2.000e-07, 1.500e-07,
        1.000e-07, 8.000e-08, 6.000e-08, 5.000e-08, 4.000e-08, 2.530e-08,
        1.000e-08, 4.000e-09]),
 array([6.20595e-05, 2.21995e-04, 4.03066e-04, 7.81542e-04, 3.46500e-04,
        3.58204e-04, 4.57929e-04, 2.04040e-04, 2.91654e-04, 2.62472e-04,
        3.03122e-04, 1.61084e-04, 2.04052e-04, 6.61394e-04, 3.07537e-04,
        5.02355e-05, 4.30194e-04, 1.37404e-04, 6.38476e-04, 4.34920e-06,
        1.